name: release
on:
  push:
    tags:
      - "v*"
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y git build-essential libssl-dev libplist-dev

      - name: Install ldid from source
        run: |
          git clone https://github.com/tpoechtrager/ldid.git
          cd ldid
          make
          sudo install -m 755 ldid /usr/local/bin/ldid

      - name: Run the build script
        uses: cli/gh-extension-precompile@v1
        with:
          build_script_override: "script/build.sh"