name: release
on:
  push:
    tags:
      - "v*"
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Install ldid
        run: sudo apt-get update && sudo apt-get install -y ldid

      - name: Run the build script
        uses: cli/gh-extension-precompile@v1
        with:
          build_script_override: "script/build.sh"